
spring:
  data:
    mongodb:
      uri: mongodb://localhost/joblisting
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
    port: 9000

springdoc:
  show-actuator: true

management:
  server:
    port: 9090